// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDROIrYltvYtH1MG1ApoGldIMD8eNMkfI8',
    appId: '1:974408789780:web:8c9f0e6b0d4a5f3a5c5c01',
    messagingSenderId: '974408789780',
    projectId: 'fat-app-c7ef0',
    authDomain: 'fat-app-c7ef0.firebaseapp.com',
    storageBucket: 'fat-app-c7ef0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDROIrYltvYtH1MG1ApoGldIMD8eNMkfI8',
    appId: '1:974408789780:android:1a6a03245d88f94f5c5c01',
    messagingSenderId: '974408789780',
    projectId: 'fat-app-c7ef0',
    storageBucket: 'fat-app-c7ef0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ20ZEaIRKmAi4H1SlfPId_bQo2NuJYG0',
    appId: '1:974408789780:ios:4ed28ee770388e6d5c5c01',
    messagingSenderId: '974408789780',
    projectId: 'fat-app-c7ef0',
    storageBucket: 'fat-app-c7ef0.firebasestorage.app',
    iosBundleId: 'com.thisbyte.fatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ20ZEaIRKmAi4H1SlfPId_bQo2NuJYG0',
    appId: '1:974408789780:ios:4ed28ee770388e6d5c5c01',
    messagingSenderId: '974408789780',
    projectId: 'fat-app-c7ef0',
    storageBucket: 'fat-app-c7ef0.firebasestorage.app',
    iosBundleId: 'com.thisbyte.fatapp',
  );
}
